### ISSUE TITLE
All orders showing as pedning payment

### ISSUE THREAD

**Issue by magentoguyssageone** [emspay/magento2#23]
Hi,

We are facing an issue with all EMS payments like the ideal and others like credit card the IPN controller not calling and after successful payment in magento admin order stay as Pending Payment.

The Invoice also not created for all orders and not any transaction info added in order Please check below screenshots.
http://prntscr.com/p8oyda
http://prntscr.com/p8oyi9
http://prntscr.com/p8oymf

I have checked the log data and in debug log there showing like below
main.DEBUG: Request validation failed for action "EMS\Pay\Controller\Index\Ipn\Interceptor"

http://prntscr.com/p8oz2i

So please check and update us how can we solve this

Thanks

**Comment by magentoguyssageone** [comment]
Hi,

any update in this.

Thanks

**Comment by dligthart** [comment]
Hi! We are going to look into this issue.

**Comment by magentoguyssageone** [comment]
Hi,

any update on this as we moved the website live and due to this issue the order status set as Pending Payment after placing order so when we manually create invoice and shipment etc then still the order status not changing and kepp pending payment so please check this issue asap.
http://prntscr.com/pd8kou
http://prntscr.com/pd8ksh

Thanks

**Comment by magentoguyssageone** [comment]
Hi,

any update in this.
kindly update me about this issue.

Thanks

**Comment by dligthart** [comment]
The ticket is in queue, will notify you once we know more

**Comment by dligthart** [comment]
Please contact EMS support to check if you account is properly set up.

**Comment by magentoguyssageone** [comment]
Hi,

Thanks for your update and Yes our account is properly set up and it was working fine with Magento1 and now we launched our website in Magento2 and the issue started.

We have already contacted the EMS support about this and they said that response is sending from Gateway to IPN URL but then it's not working.

Please check below full replay from EMS support

Bedankt voor het voorbeeld. 

Vanuit de Gateway logs zie ik dat er een reponse  wordt verzonden maar de server niet kan bereiken. Er zijn totaal 4 pogingen geprobeerd vanuit de gateway zie onderstaande log. Is het mogelijk om te controleren waarom de server niet bereikt kon worden? Welk PHP versie staat er momenteel actief? 


, 2019-09-24 13:41:45.241[CEST/+0200] INFO [IPG.COMMON.info.HttpService] de.firstdata.ipg.common.http.service.HttpService::sendRequestAsync(644) - (uuid=XYoA@AyrVLwUhlMOzuYGgQAAAnY) - [187fd267-6f30-4fa8-a970-b389e6ab885f] attempting async call to [[http://hettek.sg-host.com/emspay/index/ipn/], errorStrategy=ErrorhandlingStrategy [timeoutMs=20000, httpCallAttempts=[HttpCallAttempt [timeMs=6500, type=ATTEMPT], HttpCallAttempt [timeMs=15000, type=WAIT], HttpCallAttempt [timeMs=6500, type=ATTEMPT], HttpCallAttempt [timeMs=15000, type=WAIT], HttpCallAttempt [timeMs=6500, type=ATTEMPT], HttpCallAttempt [timeMs=15000, type=WAIT], HttpCallAttempt [timeMs=6500, type=ATTEMPT]], numberOfAttempts=4], system truststore, [TLSv1, TLSv1.1, TLSv1.2], java cipher suites, useProxyIfConfigured=true, dontVerifyHostnames=true, checkServerTrust=false, activeThreads=2, poolSize=15, queuedTasks=0
 IP_ADDRESS=10.68.5.195
  THREAD_ID=541
    DEFAULT=info
     SYSTEM=COMMON


So please check this and update me asap so we can apply the fixes on our live website.

Thanks in advance.

**Comment by dligthart** [comment]
We have performed some tests against this url:

http://hettek.sg-host.com/emspay/index/ipn/

a PUT, POST, GET with different content-type settings returns the following output:

`<!doctype html><html lang="nl"><head ><meta charset="utf-8"/><meta name="description" content="Spyshop Sitcon.nl | Grootste spy- en beveiligingsproducten winkel sinds 2006. Kom langs in 1 van onze 5 spy stores in Amsterdam, Utrecht, Rotterdam of Maaseik. Kopen kan ook online met 24H levering in onze spionage spy shop!"/><meta name="keywords" content="spyshop, afluisterapparatuur, spy shop, spy, spy camera, spy recorders, spy gadgets, afluister apparatuur, spy apparatuur, auto volgsystemen, anti afluisterapparatuur, afluister zenders, gadgets, ip camera, netwerk camera, mini camera, wireless camera, wireless spy, recorder, real time gps tracking devices, voice recorder, track trace, geheime zender, beveiligingscameras, bewakingscameras, gps trackers, keyloggers"/><meta name="robots" content="INDEX,FOLLOW"/><meta name="title" content="Beveiligingscamera´s, alarmsystemen en spyshop producten | Sitcon BV, specialist sinds 2007"/><meta name="viewport" content="width=device-width, initial-scale=1"/><meta name="format-detection" content="telephone=no"/><title>Beveiligingscamera´s, alarmsystemen en spyshop producten | Sitcon BV, specialist sinds 2007</title><link  rel="stylesheet" type="text/css"  media="all" href="http://hettek.sg-host.com/pub/static/version1569934015/_cache/merged/da18f5b095fd78ec98f663c8eabc8b21.css" />`

**Comment by dligthart** [comment]
Please check if the IPN notification route is properly configured on your system.

**Comment by magentoguyssageone** [comment]
How and where I need to check this IPN notification?
I mean I need to check-in Magento admin if Yes then where in admin because there is not any configuration for this.

or 
any other place please help me
and any if any changed needed from the server-side etc then please also let me know.

**Comment by magentoguyssageone** [comment]
Hi,

Any update about my last comment?
Please check and update me.

Thanks in advance.

**Comment by magentoguyssageone** [comment]
Hi,

any update on this
please check my issue and update me

Thanks

**Comment by magentoguyssageone** [comment]
Hi,

Any update on this I am still waiting for your update from the last many days kindly update me as we facing issues on live websites.

Thanks

**Comment by dligthart** [comment]
We have released a new version to address this issue

**Comment by dligthart** [comment]
We have released a new version.
